// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAKCjNBsGevBenH1VkFlLI7Asukvm9ASs',
    appId: '1:216407716752:web:f484b3251e082f54763915',
    messagingSenderId: '216407716752',
    projectId: 'apteka-55788',
    authDomain: 'apteka-55788.firebaseapp.com',
    storageBucket: 'apteka-55788.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsEi1BAylk3NExDAbYcSC8ODdllz_8LK4',
    appId: '1:216407716752:android:1e0adf971980898f763915',
    messagingSenderId: '216407716752',
    projectId: 'apteka-55788',
    storageBucket: 'apteka-55788.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDmokYqmybhibYpzKnbACHOVjtcm1YbsI',
    appId: '1:216407716752:ios:0bbb90eaf8326f28763915',
    messagingSenderId: '216407716752',
    projectId: 'apteka-55788',
    storageBucket: 'apteka-55788.appspot.com',
    iosBundleId: 'pl.waw.bitmed.apteka',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDmokYqmybhibYpzKnbACHOVjtcm1YbsI',
    appId: '1:216407716752:ios:0bbb90eaf8326f28763915',
    messagingSenderId: '216407716752',
    projectId: 'apteka-55788',
    storageBucket: 'apteka-55788.appspot.com',
    iosBundleId: 'pl.waw.bitmed.apteka',
  );
}
